# -*- coding: utf-8 -*-
"""Homework-1st

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rOSOAoiZCPYoO95q9FlLYDgdJuihGo4p
"""

print("Hello world")

15/4

10%4

5**2

5**3

5**4

print(10+45)
print(10+10)

x=50

print(x)

x=10
y=15
z=20

print (x, y, z)

x=y+z

print(x)

type(x)

y=3.2

type(y)

z="Azad Baig"

type(z)

dividend=100
divisor=10

dividend/divisor

marks=[10, 15, 20, 25, 30]

marks[2]

marks[-2]

marks[2:3]

marks[2:4]

marks[2:]



str1="Azad"
Str2="Baig"

print (str1+Str2)

print (str1+ " "+Str2)

print(str1+ ", "+Str2)

print(str1, Str2, sep=",")

x=15
y=15
z=15

print(x)

print(y)

print(z)

x, y, z= 10, 15, 20

print(x,y,z)

print(x,y,z, sep=":")

print(x,y,z, sep=",")

x,y,z= 10, 15.63, "azad"

print(x,y,z)

x=input()

y=input()

result=x+y

def add_three(input_var)

var = "News for all"

print(var)

x=10
y=15
z=20

print(x)

name="Rahman"
Age=45
Salary=120

print(name, Age, Salary, sep=",")

number=100

print(number)

print("Before declare: ", number)

number=120

print("After re-declare: ", number)

